AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Mostafa Elsheikh | Udacity 2021
  AWS CloudFormation Template for Udagram network in a single Availability Zone
Parameters:
  EnvironmentName:
    Description: Environment Name
    Type: "String"
    Default: "udagram-app"
  StageName:
    Description: Stage Name
    Type: "String"
    Default: "dev"
    AllowedPattern: "dev|test|pre-prod|prod"
  ComponentNumber:
    Description: Template Number as a Component
    Type: "Number"
  PublicSubnetCIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: "String"
    Default: 10.0.0.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  PrivateSubnetCIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: "String"
    Default: 10.0.2.0/24
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-${StageName}-udagram-vpc"
      AvailabilityZone: !Select [ !Ref ComponentNumber, !GetAZs "" ]
      CidrBlock: !Ref PublicSubnetCIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Network
          Value: Public
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Stage
          Value: !Ref StageName
        - Key: Name
          Value: !Sub "Public Subnet (AZ${ComponentNumber})"
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-${StageName}-udagram-vpc"
      AvailabilityZone: !Select [ !Ref ComponentNumber, !GetAZs "" ]
      CidrBlock: !Ref PrivateSubnetCIDR
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Network
          Value: Private
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Stage
          Value: !Ref StageName
        - Key: Name
          Value: !Sub "Private Subnet (AZ${ComponentNumber})"
  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: udagram-vpc
      Tags:
        - Key: Network
          Value: Public
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Stage
          Value: !Ref StageName
        - Key: Name
          Value: !Sub "IGW Elastic IP (AZ${ComponentNumber})"
  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Network
          Value: Public
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Stage
          Value: !Ref StageName
        - Key: Name
          Value: !Sub "Public NatGateway (AZ${ComponentNumber})"
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Fn::ImportValue: !Sub "${EnvironmentName}-${StageName}-prt"
      SubnetId: !Ref PublicSubnet
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-${StageName}-udagram-vpc"
      Tags:
        - Key: Network
          Value: Private
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Stage
          Value: !Ref StageName
        - Key: Name
          Value: !Sub "Private Routes (AZ${ComponentNumber})"
  DefaultPrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway
  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet
Outputs:
  PublicSubnet:
    Description: Reference to Public Subnet (AZ)
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub "${EnvironmentName}-${StageName}-public-subnet-${ComponentNumber}"
  PrivateSubnet:
    Description: Reference to Private Subnet (AZ)
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub "${EnvironmentName}-${StageName}-private-subnet-${ComponentNumber}"
